import fs from 'fs';
import path from 'path';
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const pdf = require('pdf-parse');

const MODELS_DIR = path.join(process.cwd(), 'public', 'esermiktar');
const PDF_PATH = path.join(MODELS_DIR, 'Eser_tanimlari.pdf');
const OUTPUT_FILE = path.join(process.cwd(), 'src', 'data', 'projects.js');

const MODELS = [
  'derricksalvo',
  'deuce',
  'helmora',
  'monulit',
  'prowl',
  'scarch600void',
  'seizor'
];

async function generateData() {
  let pdfText = '';
  try {
    if (fs.existsSync(PDF_PATH)) {
      const dataBuffer = fs.readFileSync(PDF_PATH);
      const data = await pdf(dataBuffer);
      pdfText = data.text;
    }
  } catch (err) {
    console.error('Failed to parse PDF:', err);
  }

  // Simple heuristic to extract descriptions if they are structured like "Model Name: Description"
  // For now, we will just use dummy descriptions or search for the model name in the text.
  
  const projects = [];

  for (const model of MODELS) {
    const modelPath = path.join(MODELS_DIR, model);
    if (!fs.existsSync(modelPath)) continue;

    // Find a cover image (first file in folder '1')
    const folder1 = path.join(modelPath, '1');
    let coverImg = '';
    if (fs.existsSync(folder1)) {
      const files = fs.readdirSync(folder1).filter(f => !f.startsWith('.'));
      if (files.length > 0) {
        coverImg = `esermiktar/${model}/1/${files[0]}`;
      }
    }

    // Try to extract description from PDF by looking for the model name
    let description = `Description for ${model}.`;
    const regex = new RegExp(`(?<=${model})[\\s\\S]*?(?=(?:${MODELS.join('|')}|$))`, 'i');
    const match = pdfText.match(regex);
    if (match && match[0].trim()) {
      description = match[0].trim();
    }

    // Read all images from ALL subfolders (handles '4(realfoto)', '4(real foto)' etc.)
    const allImages = [];
    const subDirs = fs.readdirSync(modelPath)
      .filter(f => !f.startsWith('.') && fs.statSync(path.join(modelPath, f)).isDirectory())
      .sort((a, b) => {
        // Sort by the leading number in folder name (1, 2, 3, 4(...), 5, 6)
        const numA = parseInt(a.match(/^\d+/)?.[0] || '99');
        const numB = parseInt(b.match(/^\d+/)?.[0] || '99');
        return numA - numB;
      });

    for (const subDir of subDirs) {
      const folderNum = parseInt(subDir.match(/^\d+/)?.[0] || '0');
      const folderPath = path.join(modelPath, subDir);
      const files = fs.readdirSync(folderPath).filter(f => !f.startsWith('.')).sort();
      
      for (const file of files) {
        const ext = path.extname(file).toLowerCase();
        const isVideo = ['.mp4', '.mov', '.webm', '.avi'].includes(ext);
        
        allImages.push({
          folder: folderNum,
          src: `esermiktar/${model}/${subDir}/${file}`,
          type: isVideo ? 'video' : 'image'
        });
      }
    }

    projects.push({
      id: model,
      title: model.toUpperCase(),
      coverImage: coverImg,
      description: description,
      tags: ['AI', 'Model', 'Design'],
      images: allImages
    });
  }

  const jsContent = `// Auto-generated by generate-data.js
export const PROJECTS = ${JSON.stringify(projects, null, 2)};
`;

  if (!fs.existsSync(path.dirname(OUTPUT_FILE))) {
    fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  }

  fs.writeFileSync(OUTPUT_FILE, jsContent, 'utf-8');
  console.log('Successfully generated src/data/projects.js');
}

generateData();
